export const ENABLE_DOUJIN_MODE = 'ENABLE_DOUJIN_MODE'
export const DISABLE_DOUJIN_MODE = 'DISABLE_DOUJIN_MODE'

export const UPDATE_DATA = 'UPDATE_DATA'
export const UPDATE_JACKET_DATA = 'UPDATE_JACKET_DATA'
